"""hotels category district rating + seed Кемер

Revision ID: 6c9f1a3e7b21
Revises: 1f2c9a7e5b3d
Create Date: 2026-08-25 00:00:00.000000

Список отелей зоны доставки Кемера от клиента (файл "Отели .docx"),
распознан из абзацев (не таблица): 615 строк текста, 345 отелей,
3 позиции не распознаны и в сид не попали — не выдумываем данные:

  - "Arikan Park Hotel" — рейтинг в файле обрублен до ",1" (без первой
    цифры), похоже на артефакт копирования из таблицы с объединёнными
    ячейками. rating=NULL, ждём уточнения у клиента.
  - "Deja Vu Boutique" — та же поломка, рейтинг ",4". rating=NULL.
  - "Kilikiya Resort Camyuva 5" (без района) — похоже на битый дубль
    "Kilikya Resort Camyuva 5 Чамьюва" (полная запись есть в списке
    отдельной строкой, с другим написанием Kilikiya/Kilikya) — в сид
    не включён, полная версия под своим именем есть.

"Fortuna Kemer" в файле встречается 4 раза с разными категориями
(3*/4*/5*/HV-1) — видимо разные корпуса/категории номеров одного
комплекса. Из UNIQUE(name) наружу не вылезли: в display-имя добавлен
суффикс категории («Fortuna Kemer 3*» и т.д.), иначе в выпадающем
списке клиент не отличил бы их друг от друга.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "6c9f1a3e7b21"
down_revision: Union[str, None] = "1f2c9a7e5b3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


hotels_table = sa.table(
    "hotels",
    sa.column("name", sa.String),
    sa.column("category", sa.String),
    sa.column("district", sa.String),
    sa.column("rating", sa.Numeric),
)

# category: "2".."5" — звёздность; "HV-1"/"HV-2" — Holiday Village
# (турецкая категория all-inclusive); "Villas"/"Apts" — тип размещения,
# не звёздность
SEED = [
        {"name": 'Adalin Resort Hotel', "category": '4', "district": 'Кемер', "rating": 6},
        {"name": 'Akasia Resort', "category": '3', "district": 'Бельдиби', "rating": 4},
        {"name": 'AKKA Alinda', "category": '5', "district": 'Кемер', "rating": 9.4},
        {"name": 'Akka Antedon', "category": '5', "district": 'Бельдиби', "rating": 9.1},
        {"name": 'Akka Claros', "category": '4', "district": 'Кириш', "rating": 8.9},
        {"name": 'Akka Residence', "category": 'Villas', "district": 'Бельдиби', "rating": 10},
        {"name": 'Alerya', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Alkoclar Exclusive', "category": '5', "district": 'Кемер', "rating": 9.2},
        {"name": 'Alva Donna World Palace', "category": '5', "district": 'Кириш', "rating": None},
        {"name": 'Amara Club Marine Nature', "category": 'HV-1', "district": 'Бельдиби', "rating": 9.2},
        {"name": 'Amara Dolce Vita', "category": '5', "district": 'Текирова', "rating": 8.9},
        {"name": 'Amara Prestige', "category": '5', "district": 'Гёйнюк', "rating": 7.6},
        {"name": 'Ambassador', "category": '4', "district": 'Кемер', "rating": None},
        {"name": 'Ambiente', "category": '4', "district": 'Текирова', "rating": 7.6},
        {"name": 'Amore Boutique Hotel', "category": '3', "district": 'Текирова', "rating": None},
        {"name": 'Anita Blue Sky Hotel', "category": '4', "district": 'Кириш', "rating": 7.8},
        {"name": 'Anita Club Fontana Life Hotel', "category": '4', "district": 'Кириш', "rating": None},
        {"name": 'Anita Everytime Hotel', "category": '4', "district": 'Кириш', "rating": 8.7},
        {"name": 'Anita Venus Beach Hotel', "category": '4', "district": 'Бельдиби', "rating": 7.2},
        {"name": 'Aqualin Villas', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Aramis', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Ares', "category": '3', "district": 'Кемер', "rating": 7.2},
        {"name": 'Ares Blue Hotel', "category": '3', "district": 'Кириш', "rating": 8},
        {"name": 'Ares City', "category": '3', "district": 'Кемер', "rating": 7},
        {"name": 'Ares Dream', "category": '3', "district": 'Кемер', "rating": 5.8},
        {"name": 'Arikan Park Hotel', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Armas Beach', "category": '4', "district": 'Кемер', "rating": 8.7},
        {"name": 'Armas Gul Beach', "category": '4', "district": 'Кемер', "rating": 8.6},
        {"name": 'Armas Kaplan Paradise', "category": '5', "district": 'Текирова', "rating": 8.3},
        {"name": 'Armas Labada', "category": '5', "district": 'Чамьюва', "rating": 8.2},
        {"name": 'Armas Park', "category": '3', "district": 'Кемер', "rating": 10},
        {"name": 'Armeria', "category": '3', "district": 'Кемер', "rating": 7.5},
        {"name": 'Art Beach Kemer', "category": '5', "district": 'Гёйнюк', "rating": 8.5},
        {"name": 'Asdem Park', "category": '4', "district": 'Кемер', "rating": None},
        {"name": 'Asel Hotel', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Asel Resort Hotel', "category": '4', "district": 'Гёйнюк', "rating": 6},
        {"name": 'Asia Hotel', "category": '3', "district": 'Бельдиби', "rating": 6.5},
        {"name": 'Astoria', "category": '4', "district": 'Кемер', "rating": 8.8},
        {"name": 'Aura Resort Hotel', "category": '3', "district": 'Кириш', "rating": 8.4},
        {"name": 'Avantgarde Hotel Comfort', "category": '5', "district": 'Гёйнюк', "rating": 7.5},
        {"name": 'Avantgarde Resort', "category": '5', "district": 'Гёйнюк', "rating": 9.5},
        {"name": 'Aybel Inn', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Bade', "category": '3', "district": 'Кемер', "rating": 6},
        {"name": 'Barut Kemer', "category": '5', "district": 'Кемер', "rating": 9.2},
        {"name": 'Begonya Hotel Kemer', "category": '3', "district": 'Бельдиби', "rating": 6.9},
        {"name": 'Beldiana Park', "category": '3', "district": 'Бельдиби', "rating": 7.8},
        {"name": 'Beldibi Hotel', "category": '3', "district": 'Кемер', "rating": 7.5},
        {"name": 'Beldibi Santana', "category": '3', "district": 'Бельдиби', "rating": 6.5},
        {"name": 'Belle Vue', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Belpoint Beach', "category": '4', "district": 'Бельдиби', "rating": None},
        {"name": 'Belport Beach', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Belrose Beach Hotel', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Beltur', "category": '3', "district": 'Бельдиби', "rating": 7.6},
        {"name": 'Berkay', "category": '3', "district": 'Кемер', "rating": 7.5},
        {"name": 'Berke Ranch', "category": '2', "district": 'Чамьюва', "rating": None},
        {"name": 'Beydagi Konak Hip', "category": '3', "district": 'Гёйнюк', "rating": None},
        {"name": 'Blauhimmel', "category": '4', "district": 'Чамьюва', "rating": 7.8},
        {"name": 'Bonn Beach Hotel By RRH&R', "category": '3', "district": 'Кемер', "rating": 6.4},
        {"name": 'Botanik Magic Dream Hotel', "category": '4', "district": 'Кемер', "rating": 8.2},
        {"name": 'Botanik Resort', "category": '4', "district": 'Кемер', "rating": 9.6},
        {"name": 'Britannia', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'California Dream', "category": '3', "district": 'Бельдиби', "rating": 4.1},
        {"name": 'Cam Garden', "category": '2', "district": 'Чамьюва', "rating": 4.2},
        {"name": 'Camyuva Beach', "category": '4', "district": 'Чамьюва', "rating": 9.1},
        {"name": 'Canada', "category": '3', "district": 'Кемер', "rating": 9},
        {"name": 'Carelta Beach Resort & Spa', "category": '4', "district": 'Бельдиби', "rating": None},
        {"name": 'Carpathia', "category": '3', "district": 'Гёйнюк', "rating": None},
        {"name": 'Castle Park Hotel', "category": '3', "district": 'Бельдиби', "rating": 8.8},
        {"name": 'Catamaran Resort', "category": '5', "district": 'Бельдиби', "rating": 7.9},
        {"name": 'Champion Holiday Village', "category": 'HV-1', "district": 'Бельдиби', "rating": None},
        {"name": 'Club Akman Beach', "category": '4', "district": 'Чамьюва', "rating": None},
        {"name": 'Club Beach Park', "category": '3', "district": 'Кемер', "rating": 7.2},
        {"name": 'Club Boran Mare Beach', "category": '5', "district": 'Гёйнюк', "rating": None},
        {"name": 'Club Herakles', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Club Hotel Beldiana', "category": '4', "district": 'Бельдиби', "rating": None},
        {"name": 'Club Hotel Belpinar', "category": '4', "district": 'Бельдиби', "rating": 8},
        {"name": 'Club Hotel Maximas Beach', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Club Hotel Phaselis Rose', "category": '5', "district": 'Текирова', "rating": 8.3},
        {"name": 'Club Hotel Rama', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Club Hotel Sunbel', "category": '4', "district": 'Бельдиби', "rating": 8.6},
        {"name": 'Club Marakesh Beach Hotel', "category": '4', "district": 'Бельдиби', "rating": None},
        {"name": 'Club Marco Polo', "category": '5', "district": 'Чамьюва', "rating": 8.6},
        {"name": 'Club Marekesh Beach Hotel', "category": '4', "district": 'Бельдиби', "rating": None},
        {"name": 'Club Med Kemer', "category": 'HV-1', "district": 'Кемер', "rating": None},
        {"name": 'Club Med Kemer Palmiye', "category": 'HV-1', "district": 'Гёйнюк', "rating": 9.4},
        {"name": 'Club Palm Beach Hotel', "category": '4', "district": 'Бельдиби', "rating": None},
        {"name": 'Club Phaselis', "category": 'HV-1', "district": 'Гёйнюк', "rating": 8.5},
        {"name": 'Club Salima', "category": 'HV-1', "district": 'Бельдиби', "rating": 8.1},
        {"name": 'Club Zigana', "category": 'HV-1', "district": 'Бельдиби', "rating": None},
        {"name": 'Crystal Aura Beach Resort & Spa', "category": '5', "district": 'Кемер', "rating": 8.6},
        {"name": 'Crystal De Luxe Resort & Spa', "category": '5', "district": 'Кемер', "rating": None},
        {"name": 'Crystal Flora Beach Resort', "category": '5', "district": 'Бельдиби', "rating": 8.6},
        {"name": 'Daima Biz', "category": '5', "district": 'Кириш', "rating": None},
        {"name": 'Daima Resort', "category": '5', "district": 'Кириш', "rating": 7.6},
        {"name": 'Deja Vu Boutique', "category": '4', "district": 'Чамьюва', "rating": None},
        {"name": 'Demirkaya Villa', "category": 'Villas', "district": 'Чамьюва', "rating": None},
        {"name": 'Derin', "category": '3', "district": 'Бельдиби', "rating": 7},
        {"name": 'Derus', "category": '3', "district": 'Чамьюва', "rating": None},
        {"name": 'Derya Deniz', "category": '3', "district": 'Кемер', "rating": 7},
        {"name": 'Dinara', "category": 'Apts', "district": 'Кемер', "rating": 8.6},
        {"name": 'Dinara Garden', "category": '3', "district": 'Кемер', "rating": 5.4},
        {"name": 'Dosinia Luxury Resort', "category": '5', "district": 'Бельдиби', "rating": 7.6},
        {"name": 'DoubleTree by Hilton Antalya Kemer', "category": '5', "district": 'Кемер', "rating": 8.9},
        {"name": 'Dragos Beach', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Ecem', "category": '2', "district": 'Текирова', "rating": 10},
        {"name": 'Efsane', "category": '3', "district": 'Чамьюва', "rating": 5.6},
        {"name": 'Eldar Resort', "category": '4', "district": 'Гёйнюк', "rating": 9.1},
        {"name": 'Elegan Garden', "category": '3', "district": 'Текирова', "rating": 9.1},
        {"name": 'Elegance Beach Resort', "category": '5', "district": 'Кемер', "rating": None},
        {"name": 'Elite Life', "category": '4', "district": 'Чамьюва', "rating": None},
        {"name": 'Endam', "category": '3', "district": 'Бельдиби', "rating": 7.2},
        {"name": 'Endam Garden', "category": '3', "district": 'Бельдиби', "rating": 6.8},
        {"name": 'Erkal Resort', "category": '3', "district": 'Кемер', "rating": 7.2},
        {"name": 'Esdem Garden Hotel', "category": '4', "district": 'Чамьюва', "rating": 5},
        {"name": 'Esra', "category": '2', "district": 'Кемер', "rating": 6.4},
        {"name": 'Etenna', "category": '2', "district": 'Кемер', "rating": 7.8},
        {"name": 'Euphoria', "category": '5', "district": 'Текирова', "rating": 8.7},
        {"name": 'Fame', "category": '3', "district": 'Кемер', "rating": 8.4},
        {"name": 'Fame Residence', "category": '4', "district": 'Гёйнюк', "rating": 8.8},
        {"name": 'Fame Residence Beach', "category": '4', "district": 'Кемер', "rating": 8},
        {"name": 'Fame Residence Kemer & Spa', "category": '5', "district": 'Кемер', "rating": 8.9},
        {"name": 'Fantasia Hotel De Luxe', "category": '5', "district": 'Кемер', "rating": 9},
        {"name": 'Felice', "category": '3', "district": 'Кемер', "rating": 8.1},
        {"name": 'Flower Hotel', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Flower Villa Apart', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Forest Park', "category": '3', "district": 'Кемер', "rating": 9.3},
        {"name": 'Fortuna Kemer 3*', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Fortuna Kemer 4*', "category": '4', "district": 'Кемер', "rating": None},
        {"name": 'Fortuna Kemer 5*', "category": '5', "district": 'Кемер', "rating": None},
        {"name": 'Fortuna Kemer HV-1*', "category": 'HV-1', "district": 'Кемер', "rating": None},
        {"name": 'Garden Life', "category": '3', "district": 'Кемер', "rating": 4.9},
        {"name": 'Garden Resort Bergamot', "category": '4', "district": 'Кемер', "rating": 9.5},
        {"name": 'Golden Lotus', "category": '4', "district": 'Кемер', "rating": 8.8},
        {"name": 'Golden Sun', "category": '3', "district": 'Бельдиби', "rating": 8.4},
        {"name": 'Gonul Palace', "category": '3', "district": 'Бельдиби', "rating": 6.6},
        {"name": 'Grand Haber', "category": '5', "district": 'Кемер', "rating": 9.3},
        {"name": 'Grand Hotel Derin', "category": '4', "district": 'Бельдиби', "rating": 7.1},
        {"name": 'Grand Lukullus', "category": '4', "district": 'Кемер', "rating": 7.6},
        {"name": 'Grand Mir`amor', "category": '4', "district": 'Кириш', "rating": 8.7},
        {"name": 'Grand Nar Hotel', "category": '4', "district": 'Кемер', "rating": 6.4},
        {"name": 'Grand Park Kemer', "category": '5', "district": 'Бельдиби', "rating": 8.9},
        {"name": 'Grand Ring', "category": '5', "district": 'Бельдиби', "rating": 9},
        {"name": 'Grand Viking', "category": '4', "district": 'Кемер', "rating": 9},
        {"name": 'Green Garden', "category": '2', "district": 'Бельдиби', "rating": 6},
        {"name": 'Green Stars', "category": '4', "district": 'Бельдиби', "rating": 5.1},
        {"name": 'Gural Premier Tekirova', "category": '5', "district": 'Текирова', "rating": 9},
        {"name": 'Havana', "category": '4', "district": 'Кемер', "rating": 8.9},
        {"name": 'Himeros Beach Hotel', "category": '4', "district": 'Кемер', "rating": 6},
        {"name": 'Himeros Life', "category": '4', "district": 'Кемер', "rating": 5.6},
        {"name": 'Holiday Area Farm Resort', "category": '5', "district": 'Чамьюва', "rating": 6.8},
        {"name": 'Holiday Area Green Resort', "category": '5', "district": 'Чамьюва', "rating": 6.8},
        {"name": 'Holiday Area Sea Resort', "category": '5', "district": 'Чамьюва', "rating": 7},
        {"name": 'Holiday Area Villas', "category": '5', "district": 'Чамьюва', "rating": 8.2},
        {"name": 'Hollywood', "category": '3', "district": 'Кемер', "rating": 5.3},
        {"name": 'Idyros', "category": '3', "district": 'Кемер', "rating": 7.6},
        {"name": 'Iko Melissa Garden', "category": '4', "district": 'Кемер', "rating": 5.7},
        {"name": 'Ikon Hotel', "category": '3', "district": 'Кемер', "rating": 7.1},
        {"name": 'Ilimyra', "category": '3', "district": 'Чамьюва', "rating": 5.7},
        {"name": 'Imeros', "category": '3', "district": 'Бельдиби', "rating": 7},
        {"name": 'Imperial Palace Resort', "category": '4', "district": 'Бельдиби', "rating": 10},
        {"name": 'Imperial Sunland', "category": '5', "district": 'Бельдиби', "rating": 8.8},
        {"name": 'Infinity', "category": '3', "district": 'Кемер', "rating": 7.1},
        {"name": 'Ipsos', "category": '2', "district": 'Бельдиби', "rating": 6.8},
        {"name": 'Isabel Butik', "category": '3', "district": 'Кемер', "rating": 5.8},
        {"name": 'Janina', "category": '3', "district": 'Бельдиби', "rating": 6.3},
        {"name": 'Jasmine', "category": '3', "district": 'Текирова', "rating": None},
        {"name": 'Jeans Club Hotels Festival', "category": '4', "district": 'Текирова', "rating": 8.4},
        {"name": 'Kaftans', "category": '3', "district": 'Кемер', "rating": 5},
        {"name": 'Kaliptus', "category": '2', "district": 'Кемер', "rating": 9.5},
        {"name": 'Kamilla', "category": '3', "district": 'Кемер', "rating": 4.5},
        {"name": 'Karmir Resort & Spa', "category": '5', "district": 'Гёйнюк', "rating": 8.9},
        {"name": 'Kaya Residence', "category": 'Apts', "district": 'Кемер', "rating": None},
        {"name": 'Kemer Avrupa Hotel', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Kemer Dream', "category": '4', "district": 'Кемер', "rating": 8.6},
        {"name": 'Kemer Hotel', "category": '3', "district": 'Кемер', "rating": 7.9},
        {"name": 'Kemer Houses', "category": 'Apts', "district": 'Кемер', "rating": None},
        {"name": 'Kemer Millenium Resort', "category": '5', "district": 'Кемер', "rating": 7.6},
        {"name": 'Kemer Paradise', "category": '3', "district": 'Кемер', "rating": 7.3},
        {"name": 'Kemer Park Rama', "category": '2', "district": 'Кемер', "rating": 6.3},
        {"name": 'Kemerhan', "category": '2', "district": 'Кемер', "rating": 6.4},
        {"name": 'Kilikya Palace', "category": '5', "district": 'Гёйнюк', "rating": 9},
        {"name": 'Kilikya Resort Camyuva', "category": '5', "district": 'Чамьюва', "rating": 8.7},
        {"name": 'Kimera', "category": '2', "district": 'Кемер', "rating": None},
        {"name": 'Kimeros Park Holiday Village', "category": 'HV-1', "district": 'Гёйнюк', "rating": 8.5},
        {"name": 'King', "category": '2', "district": 'Кемер', "rating": 7.4},
        {"name": 'Kiris Garden', "category": '3', "district": 'Кириш', "rating": 3.9},
        {"name": 'Konar & Doruk', "category": '3', "district": 'Кемер', "rating": 7.7},
        {"name": 'Konuk', "category": '3', "district": 'Кемер', "rating": 8.1},
        {"name": 'Korient', "category": '3', "district": 'Кемер', "rating": 8.1},
        {"name": 'Korient Mira', "category": '3', "district": 'Кемер', "rating": 7.5},
        {"name": 'L`Ancora Beach', "category": '4', "district": 'Кемер', "rating": 7.6},
        {"name": 'L`Oceanica Beach Resort', "category": '5', "district": 'Чамьюва', "rating": 9.1},
        {"name": 'Larissa', "category": '4', "district": 'Бельдиби', "rating": 7.4},
        {"name": 'Larissa Akman Park', "category": '4', "district": 'Чамьюва', "rating": 8.3},
        {"name": 'Larissa Garden', "category": '4', "district": 'Бельдиби', "rating": 6.9},
        {"name": 'Larissa Inn', "category": '4', "district": 'Чамьюва', "rating": 6.7},
        {"name": 'Larissa Mare Beach', "category": '4', "district": 'Бельдиби', "rating": 8.4},
        {"name": 'Larissa Phaselis Princess', "category": '5', "district": 'Текирова', "rating": 8.5},
        {"name": 'Larissa Sultan`s Beach', "category": '4', "district": 'Чамьюва', "rating": 9},
        {"name": 'Larissa Vista', "category": '4', "district": 'Гёйнюк', "rating": 7},
        {"name": 'Las Palmeras', "category": '4', "district": 'Чамьюва', "rating": None},
        {"name": 'Latte Beach Hotel', "category": '4', "district": 'Бельдиби', "rating": 8},
        {"name": 'Liena', "category": '3', "district": 'Текирова', "rating": 6.2},
        {"name": 'Limak Limra Club Park', "category": '4', "district": 'Кириш', "rating": 9.2},
        {"name": 'Limak Limra Hotel & Resort', "category": '5', "district": 'Кириш', "rating": 9.7},
        {"name": 'Lims Bona Dea Beach', "category": '4', "district": 'Кемер', "rating": 8.2},
        {"name": 'Lims Bona Dea Park', "category": '3', "district": 'Кемер', "rating": 7.1},
        {"name": 'Magic Dream Resort Hotel', "category": '4', "district": 'Кемер', "rating": None},
        {"name": 'Magic Sun', "category": '4', "district": 'Бельдиби', "rating": 8.1},
        {"name": 'Marin', "category": '3', "district": 'Бельдиби', "rating": 8.2},
        {"name": 'Marti Myra', "category": 'HV-1', "district": 'Текирова', "rating": 8.9},
        {"name": 'Matiate', "category": '4', "district": 'Бельдиби', "rating": 6.9},
        {"name": 'Matiate Park', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Maxx Royal Kemer Resort', "category": '5', "district": 'Кириш', "rating": 8},
        {"name": 'May Room', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Maya World Imperial Kemer', "category": '4', "district": 'Бельдиби', "rating": 7.8},
        {"name": 'Meder Resort', "category": '5', "district": 'Кемер', "rating": 8.5},
        {"name": 'Melisa Moment Apart Hotel', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Melissa Residence Hotel & SPA', "category": '4', "district": 'Кемер', "rating": 7.4},
        {"name": 'MG White Lilyum', "category": '5', "district": 'Чамьюва', "rating": 8.2},
        {"name": 'Millennium Palace', "category": '4', "district": 'Бельдиби', "rating": 7.3},
        {"name": 'Minta Apart Hotel', "category": '3', "district": 'Кемер', "rating": 8.4},
        {"name": 'Mirada del Mar', "category": '5', "district": 'Гёйнюк', "rating": 9.2},
        {"name": 'Mirage Park Resort', "category": '5', "district": 'Гёйнюк', "rating": 8.8},
        {"name": 'Miranda Moral Beach Hotel', "category": '2', "district": 'Кемер', "rating": None},
        {"name": 'MOM`s', "category": '4', "district": 'Чамьюва', "rating": 5.7},
        {"name": 'Monk Boutique Hotel', "category": '4', "district": 'Кемер', "rating": 7},
        {"name": 'More', "category": '3', "district": 'Бельдиби', "rating": 7.5},
        {"name": 'Mr. Crane', "category": '3', "district": 'Кемер', "rating": 8.5},
        {"name": 'Murat', "category": '2', "district": 'Кемер', "rating": 8},
        {"name": 'Myland Nature', "category": '2', "district": 'Кемер', "rating": None},
        {"name": 'Nar', "category": '3', "district": 'Кемер', "rating": 8.6},
        {"name": 'Naturella', "category": '2', "district": 'Кемер', "rating": 9.8},
        {"name": 'Navy Blue Stars Hotel', "category": '3', "district": 'Бельдиби', "rating": 5.1},
        {"name": 'Neo Belvista', "category": '4', "district": 'Гёйнюк', "rating": None},
        {"name": 'Nerissa', "category": '3', "district": 'Кемер', "rating": 8.8},
        {"name": 'New Bonn Resort', "category": '3', "district": 'Кемер', "rating": 5.8},
        {"name": 'New Garden Resort', "category": '4', "district": 'Кемер', "rating": 3},
        {"name": 'Nirvana Lagoon Villas Suites & Spa', "category": '5', "district": 'Бельдиби', "rating": 9},
        {"name": 'Novia Gelidonya', "category": '4', "district": 'Кемер', "rating": 8.9},
        {"name": 'Novia Lucida Beach', "category": '5', "district": 'Чамьюва', "rating": 9.2},
        {"name": 'Oasis Resort Deluxe', "category": '3', "district": 'Бельдиби', "rating": 6.1},
        {"name": 'Olimpos Beach Hotel by RRH&R', "category": '3', "district": 'Кемер', "rating": 5.4},
        {"name": 'Olympos Village', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Onkel Resort', "category": '5', "district": 'Бельдиби', "rating": 9.2},
        {"name": 'Orange County Resort', "category": '5', "district": 'Кемер', "rating": 9.6},
        {"name": 'Orange Garden', "category": 'Apts', "district": 'Кемер', "rating": 9.2},
        {"name": 'Orange Tree', "category": 'Apts', "district": 'Кемер', "rating": None},
        {"name": 'Otium Hotel Life', "category": '5', "district": 'Гёйнюк', "rating": 9.2},
        {"name": 'Ozer Park Hotel', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Ozkaymak Marina', "category": '5', "district": 'Кемер', "rating": 6.5},
        {"name": 'Ozkaymak Marina Anex', "category": '4', "district": 'Кемер', "rating": 9},
        {"name": 'Palmet Beach Resort', "category": '5', "district": 'Кемер', "rating": 8.5},
        {"name": 'Palmet Resort Kiris Hotel', "category": '5', "district": 'Кириш', "rating": 8.3},
        {"name": 'Palmet Turkiz Hotel', "category": '5', "district": 'Кемер', "rating": None},
        {"name": 'Paloma Foresta Resort & Spa', "category": '5', "district": 'Бельдиби', "rating": 9},
        {"name": 'Park Avrupa Hotel Kemer', "category": '3', "district": 'Кемер', "rating": 8.6},
        {"name": 'Park Marina', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Partmezzo Apart', "category": '3', "district": 'Кемер', "rating": 8.9},
        {"name": 'Parus', "category": '3', "district": 'Кемер', "rating": 6},
        {"name": 'Pasam', "category": '3', "district": 'Бельдиби', "rating": 7.6},
        {"name": 'Pasha`s Princess', "category": '4', "district": 'Чамьюва', "rating": None},
        {"name": 'Perre La Mer Hotel', "category": '5', "district": 'Гёйнюк', "rating": 8.2},
        {"name": 'PGS Hotels Kiris Resort', "category": '5', "district": 'Кириш', "rating": 8.8},
        {"name": 'PGS Rose Residence', "category": '5', "district": 'Кемер', "rating": 9.3},
        {"name": 'Phaselis Hill Resort', "category": '5', "district": 'Гёйнюк', "rating": 8},
        {"name": 'Pine House', "category": '4', "district": 'Чамьюва', "rating": 8.1},
        {"name": 'Pirate`s Beach Club', "category": '5', "district": 'Текирова', "rating": 8.8},
        {"name": 'Premier Palace', "category": '5', "district": 'Бельдиби', "rating": 8.5},
        {"name": 'Presa Di Finica Hotel & Suites', "category": '5', "district": 'Финике', "rating": 9},
        {"name": 'Queen`s Park Goynuk', "category": '5', "district": 'Гёйнюк', "rating": 8.8},
        {"name": 'Queen`s Park Le Jardin', "category": '5', "district": 'Кириш', "rating": 9},
        {"name": 'Queen`s Park Tekirova', "category": '5', "district": 'Текирова', "rating": 9.1},
        {"name": 'Queen`s Park Turkiz Family Club', "category": 'Apts', "district": 'Кемер', "rating": 8.9},
        {"name": 'Queen`s Park Turkiz Kemer', "category": '5', "district": 'Кемер', "rating": 7.8},
        {"name": 'Rama Beach', "category": '4', "district": 'Бельдиби', "rating": 7.7},
        {"name": 'Red Stars Anex Hotel', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Residence Rivero', "category": '4', "district": 'Кемер', "rating": 7.9},
        {"name": 'Ring Beach', "category": '5', "district": 'Бельдиби', "rating": 8.6},
        {"name": 'Rios Beach', "category": '4', "district": 'Бельдиби', "rating": 7},
        {"name": 'Rivero Park Hotel', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Rixos Beldibi', "category": '5', "district": 'Бельдиби', "rating": 8.6},
        {"name": 'Rixos Premium Tekirova', "category": '5', "district": 'Текирова', "rating": 9.1},
        {"name": 'Rixos Sungate', "category": '5', "district": 'Бельдиби', "rating": 9.5},
        {"name": 'Robinson Club Camyuva', "category": 'HV-1', "district": 'Чамьюва', "rating": 9.8},
        {"name": 'Romeo Beach', "category": '3', "district": 'Кемер', "rating": 7.4},
        {"name": 'Rose', "category": '3', "district": 'Кемер', "rating": 7.9},
        {"name": 'Rose Resort', "category": '4', "district": 'Кемер', "rating": 8.1},
        {"name": 'Rose Xiza Beach Resort', "category": '4', "district": 'Кемер', "rating": None},
        {"name": 'Royal Batont Hotel', "category": '4', "district": 'Гёйнюк', "rating": 8.2},
        {"name": 'Royal Sultan Garden', "category": 'HV-2', "district": 'Текирова', "rating": 6.9},
        {"name": 'Sah Inn Paradise', "category": '5', "district": 'Кемер', "rating": 8},
        {"name": 'Sailor`s Beach Club', "category": 'HV-1', "district": 'Кириш', "rating": 8.7},
        {"name": 'Sea Gull', "category": '4', "district": 'Бельдиби', "rating": 9.3},
        {"name": 'Sefikbey City Hotel', "category": '3', "district": 'Кемер', "rating": 7.1},
        {"name": 'Sefikbey Hotel', "category": '3', "district": 'Кемер', "rating": 6.2},
        {"name": 'Seker Ferien Haus', "category": '3', "district": 'Кириш', "rating": 4.8},
        {"name": 'Seker Resort', "category": '3', "district": 'Чамьюва', "rating": 8.8},
        {"name": 'Selcukhan', "category": '4', "district": 'Бельдиби', "rating": 8.7},
        {"name": 'Selimhan', "category": '3', "district": 'Кемер', "rating": 5.6},
        {"name": 'Sentido Sultan Beldibi', "category": '4', "district": 'Бельдиби', "rating": 9.2},
        {"name": 'Seven Seasons Hotel Cirali', "category": '4', "district": 'Кемер', "rating": 7.6},
        {"name": 'Sherwood Exclusive Kemer', "category": '5', "district": 'Гёйнюк', "rating": 8.6},
        {"name": 'Sherwood Greenwood Resort', "category": '4', "district": 'Гёйнюк', "rating": 8.6},
        {"name": 'Simena', "category": '5', "district": 'Чамьюва', "rating": 8.3},
        {"name": 'Simena Holiday Village & Villas', "category": '5', "district": 'Чамьюва', "rating": None},
        {"name": 'Simena Sun Club', "category": 'HV-1', "district": 'Чамьюва', "rating": 9},
        {"name": 'Sinatra', "category": '4', "district": 'Чамьюва', "rating": 9},
        {"name": 'Sirius', "category": '4', "district": 'Текирова', "rating": 8.8},
        {"name": 'Solim', "category": '3', "district": 'Чамьюва', "rating": 8.1},
        {"name": 'Stardust Beach', "category": '3', "district": 'Чамьюва', "rating": 7.2},
        {"name": 'Starlife', "category": '3', "district": 'Кириш', "rating": 7.8},
        {"name": 'Stella', "category": '4', "district": 'Чамьюва', "rating": 8.2},
        {"name": 'Sumela Garden', "category": '3', "district": 'Бельдиби', "rating": 7.4},
        {"name": 'Sunland Beach', "category": '3', "district": 'Кемер', "rating": 7.6},
        {"name": 'Sunshine Mir', "category": '3', "district": 'Бельдиби', "rating": 6.7},
        {"name": 'Tac Beach Club', "category": '3', "district": 'Бельдиби', "rating": 3.3},
        {"name": "Tac'un Nisa Resort", "category": '5', "district": 'Текирова', "rating": 6.3},
        {"name": 'Tal', "category": '3', "district": 'Бельдиби', "rating": 7},
        {"name": 'Tokay Hotel', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Trance Atlantic', "category": '5', "district": 'Гёйнюк', "rating": 7.6},
        {"name": 'Tropicano Family Villas', "category": 'Villas', "district": 'Кемер', "rating": 6},
        {"name": 'Trua Hotel Beldibi', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'TUI Day&Night Connected Club Hydros', "category": 'HV-1', "district": 'Кемер', "rating": 9.4},
        {"name": 'TUI Fun&Sun Club Saphire', "category": '5', "district": 'Текирова', "rating": 8.3},
        {"name": 'TUI Fun&Sun Miarosa Ghazal Resort', "category": '5', "district": 'Гёйнюк', "rating": 9.2},
        {"name": 'Tuncer Garden Boutique Hotel', "category": '3', "district": 'Кемер', "rating": 9.8},
        {"name": 'Turkiz Apartment', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Turkuaz', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Twins Hotel', "category": '3', "district": 'Кириш', "rating": 6},
        {"name": 'Ulusoy Kemer Holiday Club', "category": 'HV-1', "district": 'Гёйнюк', "rating": None},
        {"name": 'Valeri Beach', "category": '3', "district": 'Кемер', "rating": 8.7},
        {"name": 'Venera Garden Hotel', "category": '3', "district": 'Кемер', "rating": None},
        {"name": 'Viking Apart Hotel', "category": '3', "district": 'Кемер', "rating": 8.6},
        {"name": 'Viking Moral Beach', "category": '2', "district": 'Кемер', "rating": 6.4},
        {"name": 'Viking Nona Beach', "category": '4', "district": 'Кемер', "rating": 8.5},
        {"name": 'Viking Star', "category": '5', "district": 'Кемер', "rating": 8.8},
        {"name": 'Villa Flower Boutique', "category": '3', "district": 'Чамьюва', "rating": 7.8},
        {"name": 'Villa Turseb', "category": 'Villas', "district": 'Кемер', "rating": None},
        {"name": 'Villa Var Village', "category": 'Villas', "district": 'Чамьюва', "rating": 10},
        {"name": 'Wassermann', "category": '3', "district": 'Кемер', "rating": 7.7},
        {"name": 'Woodline', "category": '3', "district": 'Гёйнюк', "rating": 8},
        {"name": 'Yellow Stars', "category": '3', "district": 'Бельдиби', "rating": None},
        {"name": 'Zara', "category": '3', "district": 'Бельдиби', "rating": 7.5},
        {"name": 'Zena Resort', "category": '5', "district": 'Чамьюва', "rating": None}
]


def upgrade() -> None:
    op.add_column("hotels", sa.Column("category", sa.String(length=10), nullable=True))
    op.add_column("hotels", sa.Column("district", sa.String(length=100), nullable=True))
    op.add_column("hotels", sa.Column("rating", sa.Numeric(3, 1), nullable=True))
    op.create_index("ix_hotels_district", "hotels", ["district"])
    op.bulk_insert(hotels_table, SEED)


def downgrade() -> None:
    op.execute(
        sa.delete(hotels_table).where(
            hotels_table.c.name.in_([h["name"] for h in SEED])
        )
    )
    op.drop_index("ix_hotels_district", table_name="hotels")
    op.drop_column("hotels", "rating")
    op.drop_column("hotels", "district")
    op.drop_column("hotels", "category")
