"""promo codes max uses and used count

Revision ID: 987b9a409988
Revises: 09536229173a
Create Date: 2026-08-20 14:34:08.279119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987b9a409988'
down_revision: Union[str, None] = '09536229173a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('max_uses', sa.Integer(), nullable=True))
    op.add_column('promo_codes', sa.Column('used_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_codes', 'used_count')
    op.drop_column('promo_codes', 'max_uses')
    # ### end Alembic commands ###
